### ISSUE TITLE
Rails 3.1

### ISSUE THREAD

**Issue by jocubeit** [lucasefe/themes_for_rails#30] opened 2011-05-24 00:43 UTC
Any plans to support the new Rails 3.1 asset pipeline (/app/assets/..., scss, cofffeescript)?

**Comment by lucasefe** [comment] 2011-05-24 00:51
It has been on my mind. I still need see where it fits correctly, and how to implement it properly. 

I'll get back to you :)

**Comment by bighi** [comment] 2011-07-11 18:09
Any news on this issue?

I'm really interested in it. I'm developing a Rails 3.1 project right now and I need a nice solution for this. 

I can help you test it or anything else you may need.

**Comment by lucasefe** [comment] 2011-07-11 18:18
I am almost ready to start working on this. I am waiting for the final assets pipeline release (3.1).

Thanks, I'll let you know.

**Comment by lgs** [comment] 2011-07-11 21:10
+1 

I'd be intrested too ...

**Comment by vatsu** [comment] 2011-08-11 02:27
I am willing to help implementing it. Do you have have an initial idea on how to do it, @lucasefe?

**Comment by lucasefe** [comment] 2011-08-12 02:12
@vatsu, glad to hear it. Can we try to talk about this next week? I am participating on the rallyonrails event this weekend, but after that I'll be pretty much free for taking themes_for_rails to the next level (supporting, obviously, rails 3.1). I'll be glad to give it a try!

**Comment by druewilding** [comment] 2011-08-16 11:09
I'll be very interested in this. i currently have a Rails 3.1 using themes_for_rails but it's a bit hacky. I find i have to call things with double file extension, or it can't find the mime type. For example
/themes/purple/stylesheets/style.css.css
/themes/purple/images/background.png.png

**Comment by druewilding** [comment] 2011-08-23 17:21
On 3.1 RC5 it seems we have to comment out this line in config/environments/production.rb
config.action_dispatch.x_sendfile_header = "X-Sendfile"

Otherwise send_file doesn't work correctly in assets_controller.

I don't know how well we could integrate this with Rails 3.1 asset pipeline. It expects to find files in
app/assets
lib/assets
vendor/assets
or a gem file which also contains a vendor/assets

None of these seem to fit themes_for_rails as it currently exists. What ideas do you have?

**Comment by vatsu** [comment] 2011-08-31 21:53
Hey...I've been busy but I have time to discuss from now on whenever it suits to you better.

**Comment by rrouse** [comment] 2011-09-03 00:33
@sermoa Dynamically setting the asset paths might work. I haven't tried it yet. It depends on if/when Sprockets says "no more" in terms of changing the asset path.

**Comment by lucasefe** [comment] 2011-09-03 01:06
@vatsu, same happened to me. I am traveling so I really don't have enough time right now, but I am really interested on hearing your thoughts. 

@sermoa In my mind I see something like /themes/some_theme/assets being the new themes_for_rails base folder for stylesheets, javascripts and images. We should research about how to change on runtime the sprocket path to assets. Also, what I haven't decided yet is what to do about backward compatibility.

**Comment by rrouse** [comment] 2011-09-03 15:00
@lucasefe I'm not sure you need to add "assets" to the path at all. /themes/some_theme has a stylesheets and javascripts folder in it. I bet it would work just fine. It would make backwards compatibility easier if it worked.

**Comment by spieker** [comment] 2011-09-05 11:23
@sermoa to avoid double file extension, you can change the routes to look like this:

``` ruby
      match "#{theme_dir}/:theme/stylesheets/:asset" => 'themes_for_rails/assets#stylesheets', 
        :as => :base_theme_stylesheet,
        :constraints => { :asset => /.*/ }
      match "#{theme_dir}/:theme/javascripts/:asset" => 'themes_for_rails/assets#javascripts', 
        :as => :base_theme_javascript,
        :constraints => { :asset => /.*/ }
      match "#{theme_dir}/:theme/images/:asset" => 'themes_for_rails/assets#images', 
        :as => :base_theme_image,
        :constraints => { :asset => /.*/ }    end
```

I did it in my fork so you can have a look there :)

**Comment by arufanov** [comment] 2011-10-06 13:45
+1

I'd be intrested too ... Ready help to test.

**Comment by lucasefe** [comment] 2011-10-07 13:24
I am on vacaions but I am coming back in a couple of weeks. There's a branch from @tanraya that has  proposal for rails 3.1 compatibility, so if it's alright I will be merging it with master so we can finally have a themes_for_rails up to date. 

Cheers

**Comment by matbox** [comment] 2011-11-14 06:05
News on this?

**Comment by lucasefe** [comment] 2011-11-14 14:54
Hey, some work has been done here: https://github.com/lucasefe/themes_for_rails/tree/rails3.1

It was based on what @tanraya did a few months ago. I am adding some tests, so it would be ready soon, like maybe tonight. 

It's going to need proper testing, so I will be releasing a pre-gem for everyone to test and give some feedback, alright? 

Any help will be absolutely appreciated. 

I'll keep you all posted.

**Comment by lucasefe** [comment] 2011-11-15 21:11
Hey, after a lot of work (more reading than coding) I think I have 90% of the work completed. I had to deal with sprockets, so that's pretty much alpha (requires testing). 

Is there any available beta tester? please, check with me any problem. 

Thanks everyone.

**Comment by kenips** [comment] 2011-11-15 22:53
Awesome work Lucas and thank you so much. I can help testing if needed. Just wondering how you're calling Rails.application.assets.prepend_path? My current patch has some problem with it in production mode (can't modify immutable index) so just a heads up.

Thanks again for the awesome work!

**Comment by lucasefe** [comment] 2011-11-15 23:48
Currently I found a problem. To avoid conflicts with sprockets I decided to implement a different Sprocket::Environment (only for ThemesForRails), so I end up having a ThemesForRails::Assets working great as a static assets handler (at routes.rb level). 

After working a little I saw a fucking problem with SASS. Sass-rails gem register itself into the Rails's default instance of Sprockets (Rails.application.assets), so ThemesForRails's instance doesn't get SASS Support automatically. Clearly, this behaviour could happen with others template-handlers (HAML, Mustache, or whatever). As far as I know, there is no callback support on Sprockets, so ThemesForRails::Assets is not able to register to benefit itself with the same template handlers as the Rails default instance (of Sprockets). 

So while going back to my place I decided to rewrite this part of the gem. I am gonna have to hook TFR into Rails.application.assets, doing a nasty monkey patching on the method named find_asset. 

Why am I telling you all this? Because I want to know if someone else has a better idea. 

Cheers, everybody.

**Comment by lucasefe** [comment] 2011-11-16 16:01
Ok, done. I did all the changes to make it work as intended, and I am glad to announce that it is working great on my big app. Of course, it needs more testing... So please do. 

If everything goes as planned, at the end of the week I'll be releasing the 1.0 version (backward incompatible). Any thoughts on this? 

Lucas

**Comment by rrouse** [comment] 2011-11-16 16:10
One of the tenants of Rails 3 was that the API should be exposed cleanly enough so nasty monkey patches are a thing of the past. It would probably be a better idea to address this with the Core team so TFR can work (and others as well) within the asset pipeline without nasty patching.

So while you have to do this out of necessity right now, I'd go forward with the intention of getting it removed as soon as possible.

**Comment by lucasefe** [comment] 2011-11-16 16:16
@rrouse, I came up with a new approach. Please see this: 

https://github.com/lucasefe/themes_for_rails/blob/rails3.1/lib/themes_for_rails/railtie.rb#L10

And this includes the following module:

https://github.com/lucasefe/themes_for_rails/blob/rails3.1/lib/themes_for_rails/assets_finder.rb

(not my cleanest code, I know)

So... I am not doing monkey patching anymore. 

Thoughts?

**Comment by lucasefe** [comment] 2011-11-16 18:27
Ok, I've pushed a pre release gem. 

http://rubygems.org/gems/themes_for_rails/versions/1.0.0rc1

gem "themes_for_rails", "1.0.0rc1"

This gem clearly depends on 3.1.

**Comment by kenips** [comment] 2011-11-16 19:55
Any idea why I'm getting this?

```
ActionController::RoutingError (No route matches [GET] "/assets/.js"):
```

**Comment by lucasefe** [comment] 2011-11-16 20:00
Really no idea. 

Do you have any special routes? 

Are migrating now to rails 3.1 or you had 3.1 working since before upgrading themes_for_rails? 

Paste the line that is doing this request. 

Thanks

**Comment by kenips** [comment] 2011-11-16 20:16
This is a fresh 3.1 project, so in the layout I have:

```
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
```

And seems like for all css in themes they are not rendered properly (the first three are from libs and vendor), in addition to .js:

```
<link href="/assets/jquery-ui/demo-ui.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/vendor.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/lib.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/.css?body=1" media="screen" rel="stylesheet" type="text/css" />
```

Should mention that switching to theme_*_tag doesn't make a difference.

**Comment by kenips** [comment] 2011-11-16 20:18
Also, Lucas, in asset_finder.rb, you're already including CommonMethods, so shouldn't add_theme_assets_path be removed?

**Comment by lucasefe** [comment] 2011-11-16 20:29
This is weird, man. I tested it on my main application and on clean/new app. It works alright. 

Can you tell the name of the theme you are using? Also, please, paste the content application.css. Thanks.

**Comment by kenips** [comment] 2011-11-16 20:37
Lucas, this will hopefully help! I realize for js same thing is happening:

Output:

``` javascript
script src="/assets/jquery.js?body=1" type="text/javascript"></script>
script src="/assets/jquery-ui.js?body=1" type="text/javascript"></script>
script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script>
script src="/assets/jquery.form.js?body=1" type="text/javascript"></script>
script src="/assets/jquery.metadata.js?body=1" type="text/javascript"></script>
script src="/assets/jquery.pjax.js?body=1" type="text/javascript"></script>
script src="/assets/vendor.js?body=1" type="text/javascript"></script>
script src="/assets/.js?body=1" type="text/javascript"></script>
script src="/assets/.js?body=1" type="text/javascript"></script>
script src="/assets/.js?body=1" type="text/javascript"></script>
script src="/assets/.js?body=1" type="text/javascript"></script>
script src="/assets/.js?body=1" type="text/javascript"></script>
script src="/assets/application.js?body=1" type="text/javascript"></script>
```

And my application.js looks like this:

```
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require vendor
//= require_tree .
```

The problem comes down to this line:

```
//= require_tree .
```

If I change require_tree to require <filename> for each of the file then it works perfectly. So somehow sprockets is screwed up in rendering the filenames from require_tree.

Update: don't know how to post script tags here, removed "<"

**Comment by kenips** [comment] 2011-11-16 21:52
I decided to go back and start a brand new application. So stock Rails 3.1.1, added gem, modified routes, rails generate themes_ for_ rails:install, added a controller, and added another theme named purple. I placed one copy of test.css.scss to each stylesheets folder under themes/<name>/assets/stylesheets, and changed their values so they were different. Updated each application.html.erb to use theme_*_tag.

Still couldn't get application.css to pick up test.css.scss using require_tree .

Any ideas?

**Comment by lucasefe** [comment] 2011-11-16 21:56
I'have the same problem, FYI. The weird thing is that TFR only alters the paths of Sprockets when dealing with an assets with an uri starting with /themes/. Otherwise it leaves it as it. 

What happens if you use require_tree outside of app/themes, or maybe avoid using TFR (for diagnostic only)? It works?

**Comment by kenips** [comment] 2011-11-16 21:59
Yes my vendor.js is simply a require_tree . and it picks up all files in vendor/javascripts.

**Comment by lucasefe** [comment] 2011-11-16 22:00
So it fails if you try using this without TFR too?
If this is the case, then the problem is not related to TFR.

**Comment by kenips** [comment] 2011-11-17 16:45
No sorry it doesn't fail without TFR, but then without TFR my app assets are in app/assets rather than themes/<name>/assets. I was saying with TFR only themes/<name>/assets fails, and vendor/assets / lib/assets are fine.

**Comment by kenips** [comment] 2011-11-23 19:32
@lucasefe thanks for looking into assets. I think we can close this issue now. We can open another issue for tracking asset pipeline support if needed.

**Comment by lucasefe** [comment] 2011-11-23 19:49
@kenips I've been working on the full rails 3.1 compatibility, but it's not fully completed. There are many things that sprockets is doing, so the existing work on the rails3-1 branch is not enough no make it compatible. I've decided to push this until I have more understanding of where and how the TFR gem should hook into Sprockets. 

Just as an FYI, I tried many approaches, but non of them worked properly. I also tried  contacting the sprockets owner, but I had not response yet. 

In order to do it right, I think is better to wait. For now, we can use  TFR (master branch) with rails 3.1 but disabling assets pipeline.

Best regards.
Lucas

**Closed as completed by lucasefe** 2011-11-23 19:49 UTC

**Comment by kenips** [comment] 2011-11-23 20:06
Thanks Lucas! I'm still on [a0d3a0e6142f997d8637f4dc5166fe43be42043a](https://github.com/lucasefe/themes_for_rails/commit/a0d3a0e6142f997d8637f4dc5166fe43be42043a), but what I'm doing now is in my application.html.erb to use 

```
<%= stylesheet_link_tag "<theme-name>/application" %>
<%= javascript_include_tag "<theme-name>/application" %>
```

and keep my stylesheets and javascripts in `app/assets/stylesheets/<theme-name>` and `app/assets/javascripts/<theme-name>`. A workaround but works ok!
